provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  awesomify:
    lang: dockerfile
    handler: ./awesomify
    image: diddledan/awesomify:0.2
    environment:
      read_timeout: 10s
      write_timeout: 10s
      content_type: audio/ogg

